export const ROUTE_PATHS = {
    HOME: "/",
    LOGIN: "login",
    REGISTER: "register",
    DOCTORS: "doctors",
    DOCTOR_INFO: "doctors/:id",
	REQUEST: "request/doctor",
	RESPONSE: "response",
    ARTICLES: "articles",
    ADD_ARTICLE: "add-article",
    ARTICLE_DETAIL: "articles/:id",
    EDIT_ARTICLE: "/articles/edit/:id",
    DOCTOR_PROFILE: "profile",
    MY_ARTICLES: "my-articles",
    DOCTOR_QUERIES: "doctor-queries",
};